# Generated by Django 4.2.11 on 2024-05-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_historicalperformancemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='average_response_time',
            field=models.DateTimeField(blank=True, default=0, null=True),
        ),
    ]
