# Generated by Django 4.2.11 on 2024-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_model_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user_model',
            old_name='role',
            new_name='user_role',
        ),
        migrations.RenameField(
            model_name='vendor_model',
            old_name='vendor_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='purchase_order_model',
            name='items',
        ),
        migrations.AlterField(
            model_name='user_model',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order_model',
            name='items',
            field=models.ManyToManyField(related_name='purchase_items', to='app.items_model'),
        ),
    ]
