# Generated by Django 4.2.11 on 2024-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vendormodel_average_response_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='average_response_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
