# Generated by Django 4.2.11 on 2024-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vendormodel_average_response_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperformancemodel',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='historicalperformancemodel',
            name='to_date',
        ),
        migrations.AddField(
            model_name='historicalperformancemodel',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalperformancemodel',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
