# Generated by Django 4.2.11 on 2024-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_historicalperformancemodel_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformancemodel',
            name='average_response_time',
            field=models.TimeField(default=None),
        ),
    ]
